---
title: "HW1"
output:
  word_document: default
  html_document: default
---

### Load Packages
```{r}
library(numDeriv)
library(tidyverse)
```
       
### bisection method function
```{r}
rf_by_bisec <- function(func, a,b, thres=10^(-10), maxiter=1000) {
  x <- (a+b)/2   # starting point
  error <- 1        # stopping rule: abs conv. criterion
  niter <- 0      # number of iteration
  
  while(niter <= maxiter & error >= thres) {
    
    # get derivative of g(x) at a,x by genD function
    d <- genD(func, c(a,x))$D[1:2, 1:2]  
    
    # update interval 
    if (d[1,1] * d[2,2] <= 0) {b <- x}
    else {a <- x}
    
    #update x
    x_1 <- x    # previous x
    x <- (a+b)/2 # new x
    
    # update error and niter
    error <- abs(x_1 - x)
    niter <- niter + 1
    
    # print result of step
    print(paste(niter, x, error, a, b, sep=" "))
    
  }
  
  return(x)
  
}
```
        
        
### function 1.
$g(x) = 2x^2-x$
```{r}
func1 <- function(x) {2*x^2-x}
```
       
#### histogram of g(x)
```{r}
sam <- seq(-4,4, length.out=1000)
minx <- sam[which.min(func1(sam))]
data.frame(x=sam, y=func1(sam)) %>% ggplot(aes(x, y))+
  geom_line(colour="indianred1", size=1.5)+
  labs(y="g(x)", title="distribution of g(x)")+
  theme_light()+theme(plot.title = element_text(hjust=0.5))+
  geom_vline(xintercept=minx, color="seagreen3", size=1, linetype=2)+
  annotate("text", x=minx+0.5, y=5, label=paste0("x=", round(minx, 2)))
```
         
#### Get soloution by bisection method
```{r}
rf_by_bisec(func1, -4, 4)
```
```{r}
optimx1 <- rf_by_bisec(func1, -4, 4)
r1 <- genD(func1, optimx1)
r1$f0
r1$D[1,1]
```

           
           

### function 2.
$g(x) = log(x) / (1+x)$
```{r}
func2 <- function(x) {log(x) / (1+x)}
```
       
#### histogram of g(x)
```{r}
sam <- seq(1, 5, length.out=1000)
maxx <- sam[which.max(func2(sam))]
data.frame(x=sam, y=func2(sam)) %>% ggplot(aes(x, y))+
  geom_line(colour="indianred1", size=1.5)+
  labs(y="g(x)", title="distribution of g(x)")+
  theme_light()+theme(plot.title = element_text(hjust=0.5))+
  geom_vline(xintercept=maxx, color="seagreen3", size=1, linetype=2)+
  annotate("text", x=maxx+0.25, y=0.1, label=paste0("x=", round(maxx, 2)))
```
         
#### Get soloution by bisection method
```{r}
rf_by_bisec(func2, 1, 5)
```
```{r}
optimx2 <- rf_by_bisec(func2, 1, 5)
r2 <- genD(func2, optimx2)
r2$f0
r2$D[1,1]
```
           
           

### function 3.
$g(x) = \sqrt{4*x^2+x+2}/(2*x^3+2)^2$
```{r}
func3 <- function(x) {sqrt(4*x^2+x+2)/(2*x^3+2)^2}
```
       
#### histogram of g(x)
```{r}
sam <- seq(0,4, length.out=1000)
maxx <- sam[which.max(func3(sam))]
data.frame(x=sam, y=func3(sam)) %>% ggplot(aes(x, y))+
  geom_line(colour="indianred1", size=1.5)+
  labs(y="g(x)", title="distribution of g(x)")+
  theme_light()+theme(plot.title = element_text(hjust=0.5))+
  geom_vline(xintercept=maxx, color="seagreen3", size=1, linetype=2)+
  annotate("text", x=maxx+0.25, y=0.05, label=paste0("x=", round(maxx, 3)))
```
         
#### Get soloution by bisection method
```{r}
rf_by_bisec(func3, 0, 4)
```
```{r}
optimx3 <- rf_by_bisec(func3, 0, 4)
r3 <- genD(func3, optimx3)
r3$f0
r3$D[1,1]
```
