---
title: "hw6"
output: html_document
---
         
## Load packages
```{r}
library(tidyverse)
```
               
              
## Problem 1. p.157 Gamma Deviates
```{r}
### gamma deviates ###
func1 <- function(n, r) {  # n: sample 개수, r: gamma분포 parameter
  # in gamma dist
  a <- r - 1/3
  b <- 1/sqrt(9*a)
  
  niter <- 0
  reject_num <- 0
  accept_num <- 0
  samples <- c()
  
  while (accept_num < n) {
    z <- rnorm(1)   # proposal density
    u <- runif(1)   # sample for rejection
    tz <- a*((1+b*z)^3)   # t(z)
    if (tz <=0) {
      reject_num <- reject_num + 1
    }
    else if (u > exp((z^2)/2+a*log(tz/a)-tz+a)) {
      reject_num <- reject_num + 1
    }
    else {
      samples <- append(samples, tz)
      accept_num <- accept_num + 1
    }
    niter <- niter+1
  }
  cat("parameter of gamma:", r, "\n",
      "# of total iteration:", niter, "\n",
      "# of acceptance:", accept_num, "\t", "# of rejection:", reject_num, "\n",
      "acceptance ratio:", accept_num/niter)
  return(samples)
}
```


```{r}
r1 <- func1(10^4, 1)
```
```{r}
r2 <- func1(10^4, 2)
```
```{r}
r4 <- func1(10^4, 4)
```

```{r}
r10 <- func1(10^4, 10)
```
```{r}
r20 <- func1(10^4, 20)
```
```{r}
r30 <- func1(10^4, 30)
```
            
        
```{r}
# 실제 gamma(r,1) 분포에서 나온 값과 비교: qqplot
# r=1
data.frame(rs=r1) %>% ggplot(aes(sample=rs))+
  stat_qq(distribution = qgamma, dparams = c(1,1), color="indianred")+
  stat_qq_line(distribution = qgamma, dparams = c(1,1),
               color="seagreen3", size=1)+
  theme_light()+
  labs(x="Gamma quantiles with shape parameter=1",
       y="Rejection sampling result",
       title="Gamma QQplot of shape parameter=1")+
  theme(plot.title = element_text(hjust=0.5))
```
```{r}
# r=2
data.frame(rs=r2) %>% ggplot(aes(sample=rs))+
  stat_qq(distribution = qgamma, dparams = c(2,1), color="indianred")+
  stat_qq_line(distribution = qgamma, dparams = c(2,1),
               color="seagreen3", size=1)+
  theme_light()+
  labs(x="Gamma quantiles with shape parameter=2",
       y="Rejection sampling result",
       title="Gamma QQplot of shape parameter=2")+
  theme(plot.title = element_text(hjust=0.5))
```
```{r}
# r=4
data.frame(rs=r4) %>% ggplot(aes(sample=rs))+
  stat_qq(distribution = qgamma, dparams = c(4,1), color="indianred")+
  stat_qq_line(distribution = qgamma, dparams = c(4,1),
               color="seagreen3", size=1)+
  theme_light()+
  labs(x="Gamma quantiles with shape parameter=4",
       y="Rejection sampling result",
       title="Gamma QQplot of shape parameter=4")+
  theme(plot.title = element_text(hjust=0.5))
```

```{r}
# r=10
data.frame(rs=r10) %>% ggplot(aes(sample=rs))+
  stat_qq(distribution = qgamma, dparams = c(10,1), color="indianred")+
  stat_qq_line(distribution = qgamma, dparams = c(10,1),
               color="seagreen3", size=1)+
  theme_light()+
  labs(x="Gamma quantiles with shape parameter=10",
       y="Rejection sampling result",
       title="Gamma QQplot of shape parameter=10")+
  theme(plot.title = element_text(hjust=0.5))
```
```{r}
# r=20
data.frame(rs=r20) %>% ggplot(aes(sample=rs))+
  stat_qq(distribution = qgamma, dparams = c(20,1), color="indianred")+
  stat_qq_line(distribution = qgamma, dparams = c(20,1),
               color="seagreen3", size=1)+
  theme_light()+
  labs(x="Gamma quantiles with shape parameter=20",
       y="Rejection sampling result",
       title="Gamma QQplot of shape parameter=20")+
  theme(plot.title = element_text(hjust=0.5))
```
```{r}
# r=30
data.frame(rs=r30) %>% ggplot(aes(sample=rs))+
  stat_qq(distribution = qgamma, dparams = c(30,1), color="indianred")+
  stat_qq_line(distribution = qgamma, dparams = c(30,1),
               color="seagreen3", size=1)+
  theme_light()+
  labs(x="Gamma quantiles with shape parameter=30",
       y="Rejection sampling result",
       title="Gamma QQplot of shape parameter=30")+
  theme(plot.title = element_text(hjust=0.5))
```